### PR TITLE
Add Redis to Go

### PR DESCRIPTION
**Pull request by nullxDEADBEEF**

### CODE REVIEW

**Comment by AndreasPB** [comment]
Flow idea:
esb-flow

**Comment by nullxDEADBEEF** [comment]
In this PR the ESB can:
- Create messages(insert into Redis) and takes JSON,XML and YML as accepted formats. 
- Read messages into the specified format with a limit
Example:
image


Things that need to be implemented:
- Add lower bound for the limit, right now the limit just assumes you want messages from 0 - n
- Transform message into TSV
- Validating user token from the DB

**Comment by nullxDEADBEEF** [comment]
This is what it looks like after commit 16e0d6f

Screenshot 2022-06-05 at 04 13 14
Screenshot 2022-06-05 at 04 14 20

**Review by AndreasPB — APPROVED** [review]

**Pull request merged**
